### ISSUE TITLE
Current version doesn't  match the one on the documentation

### ISSUE THREAD

**Issue by gnkarn** [schmurtzm/MrDiy-Audio-Notifier#12]
Could you please confirm if this is the latest version,  "V0.61- 2022/02/22 " , as the one on the code  is a 0.4 release ,  thanks!!

**Comment by markvader** [comment]
The code and released firmwares are all for latest v0.61, I have made a pull request to copy the changelog from the readme to the main.cpp file so that it's changelog doesn't fall behind. (although really it ideally should exist in only one location)

**Comment by schmurtzm** [comment]
Thank you, it is merged. Yes it's just a missing copy/paste  😛 
If I make a new release in the future, I will remove the history from code....
