### ISSUE TITLE
Domain for MQTT

### ISSUE THREAD

**Issue by fuzzznet** [schmurtzm/MrDiy-Audio-Notifier#2]
You cannot enter a domain instead of an ip address, there are not enough characters in the input field.

**Comment by schmurtzm** [comment]
Yes it was initially limited to 16 characters, I will modify to 64 in the next push, seems OK for you ?

`char mqttServer[64];`

**Comment by schmurtzm** [comment]
If you can test with the last version, it should be OK.

**Comment by fuzzznet** [comment]
Yes, you can now download the domain without any problems. Thanks!
