### ISSUE TITLE
[Feature Request] - increase volume by 0.1 with MQTT

### ISSUE THREAD

**Issue by fuzzznet** [schmurtzm/MrDiy-Audio-Notifier#3]
Hey! Make volume control ( vol+ / vol- ) through requests in MQTT.

**Comment by schmurtzm** [comment]
Hi, can you try [this version](https://dl.dropbox.com/s/y2xl95oohin5q89/Schmurtz_ESP_Flasher_2022-02-16_124748.7z) ?
This beta firmware 0.5 include volume control with this MQTT command :
MQTT topic: "your_custom_mqtt_topic/volume"
MQTT load: + or -

The steps are + or - 0.1 each time.

You can also do it with buttons plugged on GPIO 13 (= vol -) and GPIO 14 (=vol +). Put GPIO to ground to trigger volume change. (cf. issue/request #4 )

**Comment by schmurtzm** [comment]
Feature implemented, no feedback but seems OK to me.

**Comment by fuzzznet** [comment]
Hey! I just can not run on D1 Mini. Plays for a few seconds, then freezes
and restarts =(
I have attached a link to a video with the problem.
I changed power supplies and D1 boards, everything is the same.
Perhaps the PCM5102A DAC itself is bad, I don’t know what to think anymore.

Could you remove or make it possible to turn off the server connection
melody? It's annoying at night when it sounds.

https://photos.app.goo.gl/JyTKsfyxPzwjY3Vg7

ср, 16 февр. 2022 г. в 02:55, Schmurtz ***@***.***>:
