### ISSUE TITLE
mrdiy

### ISSUE THREAD

**Issue by alfovit** [schmurtzm/MrDiy-Audio-Notifier#5]
what is the username and password to login to 192.168.4.1      ????
![image](https://user-images.githubusercontent.com/66839137/154671622-1db8a15b-8ece-44dc-b17f-b327f6bbd8ed.png)

**Comment by schmurtzm** [comment]
The login is "admin" and the password is the "AP password" that you have defined during wifi configuration.
It's not intuitive, I will specify it in the readme.
![image](https://user-images.githubusercontent.com/7110113/154676404-19e68c36-6881-4cf4-b608-dc063fd2aa9d.png)

**Comment by alfovit** [comment]
I can't set up wifi because I can't access the address 192.168.4.1, it asks for a username and password

**Comment by schmurtzm** [comment]
On the first connection it should not ask for password.
Erase the flash of your ESP and then reflash it.  You can use the script "Schmurtz_ESP_Flasher.bat" to dot it.

**Comment by alfovit** [comment]
ok

**Comment by schmurtzm** [comment]
I have added the informations in the readme now.
Is it OK for you after erasing the flash ?

**Comment by alfovit** [comment]
re-flashed, everything worked out, thanks

**Comment by schmurtzm** [comment]
OK great, so I close this one ;)
