### ISSUE TITLE
samvoice in version 0.6 not working

### ISSUE THREAD

**Issue by Hurstolds** [schmurtzm/MrDiy-Audio-Notifier#8]
Hi!  

googlevoice seems to work much better in version 0.6!  Thank you

However, when I send /samvoice/ commands, it just plays that guitar strum sound.  It's the sound it plays when connected to wifi/MQTT.  Sam no longer speaks.

Did the command change for sam?  or is it still /samvoice/
Pretty sure I'll just use googlevoice from now on, instead of sam, but I wanted to bring this to your attention

**Comment by schmurtzm** [comment]
Hi,

No the command has not changed (still "yourtopic/samvoice"), this is a real issue on ESP8266 (it works on ESP32).
The guitar strum sound is the boot sound, so if you hear it it means that the ESP has crashed and rebooted.

I've tested with 0.4 and it seems it was already crashing.

Needs some investigation ...

**Comment by schmurtzm** [comment]
Solved, it comes from a parameter in platformio.ini :
```
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH    ; crash with SAMVOICE
```

Will be removed in next release.

**Comment by schmurtzm** [comment]
Version 0.61 is published with this fix.

**Comment by Hurstolds** [comment]
All seems well, after testing 0.61!  Thank you, I did not have to do a full flash.  I was able to flash via GUI updater and it kept all my previous settings.  Great job and thank you again!
